# Generated by Django 5.2.5 on 2025-08-20 08:47

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SamplingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('sampling_method', models.CharField(choices=[('manual', '手工取样'), ('auto', '自动化取样')], max_length=10)),
                ('curve_points', models.IntegerField()),
                ('qc_groups', models.IntegerField()),
                ('qc_levels', models.IntegerField()),
                ('qc_insert', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=5)),
                ('test_count', models.IntegerField()),
                ('layout', models.CharField(blank=True, choices=[('horizontal', '横向'), ('vertical', '纵向')], max_length=10, null=True)),
                ('mapping_file', models.FileField(blank=True, null=True, upload_to=dashboard.models.upload_to_project_folder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
