# Generated by Django 5.2.5 on 2025-08-21 08:20

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_samplingconfiguration_default_upload_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=200)),
                ('instrument_num', models.CharField(max_length=200)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to=dashboard.models.upload_to_instrument_folder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
