# Generated by Django 5.2.5 on 2025-08-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_instrumentconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstrumentConfiguration',
        ),
    ]
