# Generated by Django 5.2.5 on 2025-08-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_instrumentconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionVolumeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('instrument_num', models.CharField(max_length=200)),
                ('injection_volume', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
