# Generated by Django 5.2.5 on 2025-09-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_injectionvolumeconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('plate_no', models.CharField(max_length=20)),
                ('well_str', models.CharField(max_length=10)),
                ('sample_name', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('record_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
