# Generated by Django 5.2.6 on 2025-10-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_samplerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionPlateConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('instrument_num', models.CharField(max_length=200)),
                ('injection_plate', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
