# Generated by Django 5.2.6 on 2025-10-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_injectionplateconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InjectionPlateConfiguration',
        ),
    ]
