# Generated by Django 5.2.6 on 2025-10-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_delete_injectionplateconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionPlateConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('instrument_num', models.CharField(max_length=200)),
                ('injection_plate', models.JSONField(default=list, help_text="保存为字符串列表，例如 ['Plate1','Plate2','Plate3'] ")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
