# Generated by Django 5.2.6 on 2025-10-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_injectionplateconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplingconfiguration',
            name='project_name_full',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
