# Generated by Django 5.2.6 on 2025-10-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_injectionplateconfiguration_systerm_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplingconfiguration',
            name='systerm_num',
            field=models.CharField(blank=True, choices=[('S0', 'S0'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4')], default='', max_length=10),
        ),
    ]
