# Generated by Django 5.2.6 on 2025-11-12 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_samplingconfiguration_systerm_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplerecord',
            name='record_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
