# Generated by Django 5.2.6 on 2025-11-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_samplerecord_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplerecord',
            name='error_info',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
