# Generated by Django 5.2.6 on 2026-04-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_samplerecord_error_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplerecord',
            name='batch_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
